//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CID10
    {
        public CID10()
        {
            this.FormCID10 = new HashSet<FormCID10>();
        }
    
        public int id { get; set; }
        public string codcid { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<FormCID10> FormCID10 { get; set; }
    }
}
