//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormCID10
    {
        public int id { get; set; }
        public int idFormulario { get; set; }
        public int idCID10 { get; set; }
    
        public virtual CID10 CID10 { get; set; }
        public virtual Formulario Formulario { get; set; }
    }
}
