//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocialCareEntities : DbContext
    {
        public SocialCareEntities()
            : base("name=SocialCareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TAB__MATERIAL> TAB__MATERIAL { get; set; }
        public DbSet<TAB_CID> TAB_CID { get; set; }
        public DbSet<TAB_DIAGNOSTICO> TAB_DIAGNOSTICO { get; set; }
        public DbSet<TAB_FORM> TAB_FORM { get; set; }
        public DbSet<TAB_FORM_MAT> TAB_FORM_MAT { get; set; }
        public DbSet<TAB_FORM_PROC_ENF> TAB_FORM_PROC_ENF { get; set; }
        public DbSet<TAB_PACIENTE> TAB_PACIENTE { get; set; }
        public DbSet<TAB_PROC_ENF> TAB_PROC_ENF { get; set; }
        public DbSet<TAB_PROCEDIMENTO> TAB_PROCEDIMENTO { get; set; }
        public DbSet<TAB_PROFISSIONAL> TAB_PROFISSIONAL { get; set; }
        public DbSet<TAB_SAIDA> TAB_SAIDA { get; set; }
        public DbSet<TAB_UP> TAB_UP { get; set; }
        public DbSet<TAB_VISITA> TAB_VISITA { get; set; }
        public DbSet<TAB_VISITA_PROC> TAB_VISITA_PROC { get; set; }
    }
}
