//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_UP
    {
        public int cod_up { get; set; }
        public string des_momento { get; set; }
        public string des_estagio { get; set; }
        public Nullable<System.DateTime> dat_up { get; set; }
        public int TAB_PACIENTE_cod_paciente { get; set; }
    
        public virtual TAB_PACIENTE TAB_PACIENTE { get; set; }
    }
}
