//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_FORM_PROC_ENF
    {
        public int cod_form_proc { get; set; }
        public int cod_form { get; set; }
        public int cod_proc_enf { get; set; }
    
        public virtual TAB_FORM TAB_FORM { get; set; }
        public virtual TAB_PROC_ENF TAB_PROC_ENF { get; set; }
    }
}
