//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_CID
    {
        public TAB_CID()
        {
            this.TAB_DIAGNOSTICO = new HashSet<TAB_DIAGNOSTICO>();
        }
    
        public int cod_cid { get; set; }
        public string cod_cid10 { get; set; }
        public string des_cid { get; set; }
    
        public virtual ICollection<TAB_DIAGNOSTICO> TAB_DIAGNOSTICO { get; set; }
    }
}
