//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_PACIENTE
    {
        public TAB_PACIENTE()
        {
            this.TAB_FORM = new HashSet<TAB_FORM>();
            this.TAB_SAIDA = new HashSet<TAB_SAIDA>();
            this.TAB_UP = new HashSet<TAB_UP>();
            this.TAB_VISITA = new HashSet<TAB_VISITA>();
        }
    
        public int cod_paciente { get; set; }
        public string nom_paciente { get; set; }
        public System.DateTime dat_nasc { get; set; }
        public string tel_paciente { get; set; }
        public string des_sexo { get; set; }
        public string des_end { get; set; }
        public int num_end { get; set; }
        public string des_referencia_end { get; set; }
        public string Nom_cuidador { get; set; }
        public string des_parentesco { get; set; }
        public Nullable<int> num_grau_ce { get; set; }
    
        public virtual ICollection<TAB_FORM> TAB_FORM { get; set; }
        public virtual ICollection<TAB_SAIDA> TAB_SAIDA { get; set; }
        public virtual ICollection<TAB_UP> TAB_UP { get; set; }
        public virtual ICollection<TAB_VISITA> TAB_VISITA { get; set; }
    }
}
