//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_PROFISSIONAL
    {
        public TAB_PROFISSIONAL()
        {
            this.TAB_VISITA = new HashSet<TAB_VISITA>();
        }
    
        public int cod_profissional { get; set; }
        public string nom_profissional { get; set; }
        public string des_login { get; set; }
        public string des_senha { get; set; }
        public string des_cargo { get; set; }
        public string num_rg { get; set; }
        public Nullable<System.DateTime> dat_nascimento { get; set; }
        public string des_email { get; set; }
        public Nullable<System.DateTime> dat_admissao { get; set; }
        public Nullable<System.DateTime> dat_demissao { get; set; }
        public string des_sexo { get; set; }
        public Nullable<int> num_end { get; set; }
        public string des_complemento_end { get; set; }
        public string des_referencia_end { get; set; }
        public string img_foto { get; set; }
    
        public virtual ICollection<TAB_VISITA> TAB_VISITA { get; set; }
    }
}
