//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_PROCEDIMENTO
    {
        public TAB_PROCEDIMENTO()
        {
            this.TAB_VISITA_PROC = new HashSet<TAB_VISITA_PROC>();
        }
    
        public int cod_procedimento { get; set; }
        public string nom_procedimento { get; set; }
        public string obs_procedimento { get; set; }
        public string des_categoria { get; set; }
    
        public virtual ICollection<TAB_VISITA_PROC> TAB_VISITA_PROC { get; set; }
    }
}
