//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_PROC_ENF
    {
        public TAB_PROC_ENF()
        {
            this.TAB_FORM_PROC_ENF = new HashSet<TAB_FORM_PROC_ENF>();
        }
    
        public int cod_proc_enf { get; set; }
        public string nom_proc_enf { get; set; }
    
        public virtual ICollection<TAB_FORM_PROC_ENF> TAB_FORM_PROC_ENF { get; set; }
    }
}
