//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_SAIDA
    {
        public int cod_saida { get; set; }
        public System.DateTime dat_saida { get; set; }
        public string des_razao { get; set; }
        public string des_obs { get; set; }
        public int TAB_PACIENTE_cod_paciente { get; set; }
    
        public virtual TAB_PACIENTE TAB_PACIENTE { get; set; }
    }
}
